sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head

bundler_args: "--jobs=3 --retry=3"
cache: bundler

before_install:
  - gem update bundler
